### ISSUE TITLE
The Handy stuttering

### ISSUE THREAD

**Issue by OfficialLayton** [Yoooi0/MultiFunPlayer#110] opened 2022-12-22 22:19 UTC
When I use the handy the arm vibrates erratically.

Tested on both L0 and V1 Axes.

**Comment by Yoooi0** [comment] 2022-12-22 23:18
The Handy support is marked as experimental as I don't have one to test it.
Someone who has one would need to debug MFP (if there is something wrong on MFP side).

But the issue is mainly because there is no good way to send commands directly to the handy. You either send commands via their servers which will be unstable due to round trip time, or use bluetooth which will be unstable because its bluetooth.

You could try playing with update rate on The Handy output, or try buttplug.io output which will use bluetooth.

**Closed** 2022-12-26 00:50 UTC
Labels: wontfix, issue
